CREATE TABLE IF NOT EXISTS categorys (
    `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `category` VARCHAR(255) NOT NULL UNIQUE,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAM
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO categorys (`category`) VALUES 
    ('PAKET-INTERNET'),
    ('PULSA-REGULER'),
    ('VOUCHER-GAME'),
    ('TOKEN-LISTRIK');

CREATE TABLE IF NOT EXISTS products (
    `id` INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    `category_id` INT UNSIGNED NOT NULL,
    `product_code` VARCHAR(255) NOT NULL UNIQUE,
    `name` VARCHAR(255) NOT NULL UNIQUE,
    `description` TEXT NULL,
    `buy_price` DOUBLE NOT NULL,
    `sell_price` DOUBLE NOT NULL,
    `image_url` VARCHAR(255) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAM,
    CONSTRAINT `fk_products_categorys_id` FOREIGN KEY(`category_id`) REFERENCES categorys(`id`) 
        ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;